DafpcBundle\Entity\Upload:
    type: entity
    table: null
    repositoryClass: DafpcBundle\Repository\UploadRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        file:
            type: string
            length: 255
            image: ~
    #lifecycleCallbacks: {  }
    lifecycleCallbacks:
        prePersist: [ preUpload, setCreatedAtValue, setExpiresAtValue ]
        preUpdate: [ preUpload, setUpdatedAtValue ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]