#/var/www/html/dafpc/app/config/routing.yml

upload:
    resource: "@DafpcBundle/Resources/config/routing.yml"
    prefix:   /

dafpc:
    resource: "@DafpcBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

geoloc:
    path:     /geoloc
    defaults: { _controller: AppBundle:Default:geoloc}